language: scala
scala:
- 2.11.8

env:
  global:
  - LIB_VERSION=$TRAVIS_TAG

deploy:
  provider: script
  skip_cleanup: true
  script: project/publish.sh
  env:
  on:
    tags: true

script:
  - sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=$BINTRAY_PASSWORD +compile
